import 'package:hive/hive.dart';
import '../models/package_model.dart';

// ── PackageStatus ──────────────────────────────────────────────

class PackageStatusAdapter extends TypeAdapter<PackageStatus> {
  @override
  final int typeId = 0;

  @override
  PackageStatus read(BinaryReader reader) {
    return PackageStatus.values[reader.readByte()];
  }

  @override
  void write(BinaryWriter writer, PackageStatus obj) {
    writer.writeByte(obj.index);
  }
}

// ── UrgencyLevel ───────────────────────────────────────────────

class UrgencyLevelAdapter extends TypeAdapter<UrgencyLevel> {
  @override
  final int typeId = 1;

  @override
  UrgencyLevel read(BinaryReader reader) {
    return UrgencyLevel.values[reader.readByte()];
  }

  @override
  void write(BinaryWriter writer, UrgencyLevel obj) {
    writer.writeByte(obj.index);
  }
}

// ── CourierType ────────────────────────────────────────────────

class CourierTypeAdapter extends TypeAdapter<CourierType> {
  @override
  final int typeId = 2;

  @override
  CourierType read(BinaryReader reader) {
    return CourierType.values[reader.readByte()];
  }

  @override
  void write(BinaryWriter writer, CourierType obj) {
    writer.writeByte(obj.index);
  }
}

// NOTE: PackageAdapter (typeId: 3) is generated by hive_generator
// via @HiveType annotation on the Package class.
